name: Build Gradle from default branch
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: Add JAR to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: build/libs/media-kord-*.jar
          file_glob: true
          asset_name: media-kord-$tag.jar
